name: clinicc
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  animated_custom_dropdown: ^3.1.1
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  easy_date_timeline: ^2.0.9
  file_picker: ^9.2.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  modal_progress_hud_nsn: ^0.5.1
  path_provider: ^2.0.15
  pay_with_paymob: ^1.4.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  supabase: ^2.6.3
  supabase_flutter: ^2.0.0
  timeago: ^3.7.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # هذا القسم هو المسؤول عن توليد الترجمة
  generate: true
flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false
