// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdW6PEwY8CfmIvHg2poBFfxVjSUGE_pFo',
    appId: '1:64704371071:web:d8737f41152393de8ca24a',
    messagingSenderId: '64704371071',
    projectId: 'clinc-42669',
    authDomain: 'clinc-42669.firebaseapp.com',
    storageBucket: 'clinc-42669.firebasestorage.app',
    measurementId: 'G-XRDZP7F3H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGCR8lCP9DEhNvuxcsYMaDmm4RuzyNnNo',
    appId: '1:64704371071:android:69aa48a657ce4b9d8ca24a',
    messagingSenderId: '64704371071',
    projectId: 'clinc-42669',
    storageBucket: 'clinc-42669.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxWNo5wcfYtNBj7VsLD6__GTQPfrNR_aU',
    appId: '1:64704371071:ios:a40340fbb336e6668ca24a',
    messagingSenderId: '64704371071',
    projectId: 'clinc-42669',
    storageBucket: 'clinc-42669.firebasestorage.app',
    iosBundleId: 'com.example.clinicc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxWNo5wcfYtNBj7VsLD6__GTQPfrNR_aU',
    appId: '1:64704371071:ios:a40340fbb336e6668ca24a',
    messagingSenderId: '64704371071',
    projectId: 'clinc-42669',
    storageBucket: 'clinc-42669.firebasestorage.app',
    iosBundleId: 'com.example.clinicc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdW6PEwY8CfmIvHg2poBFfxVjSUGE_pFo',
    appId: '1:64704371071:web:45e22bc5907f7cfb8ca24a',
    messagingSenderId: '64704371071',
    projectId: 'clinc-42669',
    authDomain: 'clinc-42669.firebaseapp.com',
    storageBucket: 'clinc-42669.firebasestorage.app',
    measurementId: 'G-0GMLVPH6PV',
  );
}
